#!/bin/bash

######################## < CONFIG SECTION > ########################

mac='48:27:EA:01:50:82'
delay='2'
PING='2'
ping_failed='2'
LOCK='0' # False
session_id=$(loginctl list-sessions | egrep zerocool | awk '{ print $1 }') # Get SESSION ID

##################### < END CONFIG SECTION > #####################


######################## < FUNCTION SECTION > ########################

function Check_ping {

  if [ `sudo l2ping $mac -c 1 | grep "0% loss" -c` -eq 1 ] ; then #vaut 1 si l2ping contient "0% loss"
    if [ $PING -lt 2 ]; then
      let 'PING+=1'
    fi
  else
    if [ $PING -ge 1 ]; then
      let 'PING-=1'
    fi
  fi

}

function LockUnlock {

  if [ $PING -ge 1 ] && [ $LOCK -eq 1 ] ; then

      # UNLOCK SESSION
      loginctl unlock-session $session_id

      let 'LOCK=0'

  elif [ $PING -eq 0 ] && [ $LOCK -eq 0 ]; then

    # LOCK SESSION
      loginctl lock-session $session_id

      let 'LOCK=1'
  fi

}

######################## < END FUNCTION SECTION > ########################


while [ 1 ]; do

  Check_ping
  LockUnlock
  # sleep $delay
done
