#!/bin/bash

################
# Configurable #
################
mac='44:4E:1A:D6:F5:D5'
delay='5'
nb_ping_failed='2'
nb_ping_success='2'

## END !!


let "locked=0" #Etat de l'écran
while [ 1 ]
do
  if [ $locked -ne 1 ] ; then
    let "nb=$nb_ping_success"
  else
    let "nb=$nb_ping_failed"
  fi
  let "i=nb"
    while [ $i -ne 0 ] #Tant que la connexion n'a pas foiré plus de fois qu'imposé (i décroît)
    do
      sleep $delay
      if [ `sudo l2ping $mac -c 1 | grep "0% loss" -c` -eq 1 ] ; then #vaut 1 si l2ping contient "0% loss"
        echo "Connexion réussie"
        let "link=1"
      else
        echo "Connexion ratée"
        let "link=0"
      fi
      let "a = (link + locked) % 2" # c'est juste un xor. Petite astuce pour éviter d'avoir à faire 2 paires de tests
      if [ $a -eq 1 ]  ; then
        let "i=nb"
        echo "test restant : $i"
      else
        let "i-=1"
        echo "test restant : $i"
      fi
    done #On sort de la boucle quand la connexion a réussi ou foiré trop de fois
  if [ $locked -eq 1 ] ; then
    echo "Déverrouillage"
    sh deverrouillage.sh
    let "locked=0"
  else
    echo "Verrouillage"
    sh verrouillage.sh
    let "locked=1"
  fi
done
